export const EgzersizData=[
    {
        id:1,
        source:require('./jumping.gif'),
        name: "Ayakta Alkış",
        sure:2,
        seviye:0,
        calori:123,
        aciklama:"Temel fitness hareketlerinden biridir ve kardiyo egzersizi olarak oldukça etkilidir. Tüm vücudu çalıştırır, spora başlamak için ısınma hareketi olarak kullanılır.",
    },
    {
        id:2,
        source:require('./kasgerdirme.gif'),
        name: "Ayakta Kas Gerdirme",
        sure:2,
        seviye:0,
        calori:123,
        aciklama:"Ayaklarınızı geniş biçimde açık ve elleriz kalçalarınızda durur halde ayakta durun.",
    },
    {
        id:3,
        source:require('./squat.gif'),
        name: "Squat",
        sure:2,
        seviye:0,
        calori:123,
        aciklama:"En etkili egzersizlerden biri olan squat, çok yönlü bir harekettir, Kalça, karın, uyluk ve sırt kaslarının aynı anda çalışmasını sağlar.",
    },
    {
        id:4,
        source:require('./crunch.gif'),
        name: "Crunch",
        sure:2,
        seviye:0,
        calori:123,
        aciklama:"Crunch egzersizi, vücut ağırlığınızı ile karın kaslarınızı şekillendirmenizi sağlayan bu egzersiz, birincil olarak ön karın kaslarını çalıştırır.",
    },
    {
        id:5,
        source:require('./bridge.gif'),
        name: "Köprü",
        sure:2,
        seviye:0,
        calori:123,
        aciklama:"Bridge egzersizi; bacak, kalça ve basen bölgesini şekillendirmek için yapılan etkili hareketlerden biridir.",
    },
    {
        id:6,
        source:require('./plank.jpeg'),
        name: "Plank",
        sure:2,
        seviye:0,
        calori:123,
        aciklama:"Plank egzersizi çapraz, düz ve yan karın kaslarını kapsayacak şekilde bütün karın bölgesini ve kalçanızı çalıştırır.",
    },
    {
        id:7,
        source:require('./jumping.gif'),
        name: "Jumping Jack",
        sure:2,
        seviye:1,
        calori:123,
        aciklama:"Temel fitness hareketlerinden biridir ve kardiyo egzersizi olarak oldukça etkilidir. Tüm vücudu çalıştırır, spora başlamak için ısınma hareketi olarak kullanılır.",
    },
    {
        id:8,
        source:require('./kasgerdirme.gif'),
        name: "Ayakta Kas Gerdirme",
        sure:2,
        seviye:1,
        calori:123,
        aciklama:"Ayaklarınızı geniş biçimde açık ve elleriz kalçalarınızda durur halde ayakta durun",
    },
    {
        id:9,
        source:require('./alkislama.gif'),
        name: "Alkışlama Crunch",
        sure:2,
        seviye:1,
        calori:123,
        aciklama:"Dizleriniz bükülü, ayaklarınız biraz kaldırmış ve sırtınız geriye doğru eğik olarak yere oturun. Dönüşümlü olarak bacaklarınızı kaldırın ve dizlerinizin altından alkışlama yapın.",
    },
    {
        id:10,
        source:require('./solyangın.gif'),
        name: "Sol Yangın Musluğu",
        sure:2,
        seviye:1,
        calori:123,
        aciklama:"sdlkjfhgsjdkfgjsdhfgjhsdfgkjhsdafasdfsdfhgfasdhgfsdjfjhgsakjdhfgkjahgdfjksahdfghjdskgfjaksdhfgjskdafhgskdajfg",
    },
    {
        id:11,
        source:require('./sagyangın.gif'),
        name: "Sağ Yangın Musluğu",
        sure:2,
        seviye:1,
        calori:123,
        aciklama:"sdlkjfhgsjdkfgjsdhfgjhsdfgkjhsdafasdfsdfhgfasdhgfsdjfjhgsakjdhfgkjahgdfjksahdfghjdskgfjaksdhfgjskdafhgskdajfg",
    },
        {
        id:12,
        source:require('./plank.jpeg'),
        name: "Plank",
        sure:2,
        seviye:1,
        calori:123,
        aciklama:"Ayak parmaklarınız ve kollarınızı zemin üzerinde duracak şekilde durun.",
    },
    {
        id:13,
        source:require('./z1.gif'),
        name: "Ayakta Crunch",
        sure:2,
        seviye:2,
        calori:123,
        aciklama:"Ayakta omuz genişliğinde açılmış olarak ayakta durun. Dizinizi ters dirseğinize getirin ve diğer tarafla tekrarlayın.",
    },
    {
        id:14,
        source:require('./z2.gif'),
        name: "Kalçadan Sol Tekme",
        sure:2,
        seviye:2,
        calori:123,
        aciklama:"Emekleme pozisyonuna geçin ve dizler kalçanızın hizasında, eller de omuzlarınızın hizasında olsun. Ardından sol bacağınızı kaldırın.",
    },
    {
        id:15,
        source:require('./z3.gif'),
        name: "Kalçadan Sağ Tekme",
        sure:2,
        seviye:2,
        calori:123,
        aciklama:"Emekleme pozisyonuna geçin ve dizler kalçanızın hizasında, eller de omuzlarınızın hizasında olsun. Ardından sağ bacağınızı kaldırın.",
    },
    {
        id:16,
        source:require('./z4.gif'),
        name: "Topuğa Dokunma",
        sure:2,
        seviye:2,
        calori:123,
        aciklama:"Bacaklarınızı bükülü ve elleriniz yanınızda durur şekilde yere yatın. Vücudunuzun üst kısmını biraz kaldırıp değişimli olarak topuklarınıza dokunun.",
    },
    {
        id:17,
        source:require('./z5.gif'),
        name: "Kelebek Tekmeler",
        sure:2,
        seviye:2,
        calori:123,
        aciklama:"Sırt üstü uzanın ve bacaklarınızı düz tutarak kaldırın. Sonra hızlı biçimde aynı anda sağ bacağınızı kaldırıp sol bacağınızı indirin. Bacakları değiştirip tekrar edin.",
    },
    {
        id:18,
        source:require('./plank.jpeg'),
        name: "Plank",
        sure:2,
        seviye:2,
        calori:123,
        aciklama:"Ayak parmaklarınız ve kollarınızı zemin üzerinde duracak şekilde durun.",
    },
]